server:
  port: 8071
spring:
  application:
    name: SERVICE-RES-DEMOS
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
